//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarahShaw.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RX_Job
    {
        public System.Guid Id { get; set; }
        public Nullable<int> ContractorID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Room { get; set; }
        public string DelayReason { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateDelayed { get; set; }
        public Nullable<int> StatusNum { get; set; }
        public Nullable<int> RJobID { get; set; }
        public Nullable<System.Guid> RoomTypeId { get; set; }
    }
}
